package com.thirdeye30.resumehelper.pdfgenerater.services.impl;

import com.thirdeye30.resumehelper.pdfgenerater.services.PdfGeneraterService;
import com.thirdeye30.resumehelper.pdfgenerater.services.ResumeService;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import com.thirdeye30.resumehelper.pdfgenerater.dtos.ResumeContentDto;
import com.thirdeye30.resumehelper.pdfgenerater.enums.PdfType;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.util.HtmlUtils;

import java.io.ByteArrayOutputStream;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Slf4j
public class PdfGeneraterServiceImpl implements PdfGeneraterService {

    private final ObjectMapper objectMapper;
    private final ResumeService resumeService;
    private final RestTemplate restTemplate = new RestTemplate();

    @Override
    public byte[] generatePdf(UUID resumeId, PdfType pdfType){
        
        log.info("Generating PDF for resume {} using template {}", resumeId, pdfType);
        ResumeContentDto dto = resumeService.getResumeContent(resumeId);
        String toonJsonString = null;
        if(dto.getContent() != null && dto.getContent().length() > 0)
        {
        	toonJsonString = dto.getContent();
        }
        else if(dto.getContentUrl() != null && dto.getContentUrl().length() > 0)
        {
        	log.info("Fetching TOON data from URL: {}", dto.getContentUrl());
            try {
                toonJsonString = restTemplate.getForObject(dto.getContentUrl(), String.class);
            } catch (Exception e) {
                log.error("Failed to download TOON string from URL: {}", dto.getContentUrl(), e);
                throw new RuntimeException("Failed to download resume content from URL", e);
            }
        }
        if (toonJsonString == null || toonJsonString.isBlank()) {
            throw new RuntimeException("Resume content is empty or not yet generated by AI.");
        }
        
        List<List<Object>> toonData = null;
        
        try {
            toonData = objectMapper.readValue(toonJsonString, new TypeReference<>() {});
            String htmlContent = buildHtmlFromToon(toonData, pdfType);

            try (ByteArrayOutputStream os = new ByteArrayOutputStream()) {
                PdfRendererBuilder builder = new PdfRendererBuilder();
                builder.useFastMode();
                builder.withHtmlContent(htmlContent, null);
                builder.toStream(os);
                builder.run();
                return os.toByteArray();
            }
        } catch(Exception e) {
        	log.error("unable to create pdf: {}", resumeId, e);
            throw new RuntimeException("PDF Secure Upload Failed", e);
        }
        
    }

    private String buildHtmlFromToon(List<List<Object>> toonData, PdfType type) {
        StringBuilder html = new StringBuilder();
        html.append("<html><head><style>");
        html.append(getCssForType(type));
        html.append("</style></head><body>");

        // Recursively parse the TOON data
        for (List<Object> node : toonData) {
            parseToonNode(node, html, 1);
        }

        html.append("</body></html>");
        return html.toString();
    }
    
    private String getCssForType(PdfType type) {
        switch (type) {
            case TYPE_2: 
                // MODERN (Sans-serif, blue accents)
                return "body { font-family: 'Helvetica', sans-serif; color: #333; line-height: 1.6; padding: 30px; }" +
                       "h1 { font-size: 22px; color: #2b6cb0; border-bottom: 2px solid #ebf8ff; padding-bottom: 5px; margin-top: 20px; text-transform: uppercase; }" +
                       "h2 { font-size: 16px; color: #2d3748; margin-bottom: 5px; font-weight: bold; }" +
                       "p, li { font-size: 13px; color: #4a5568; margin-bottom: 4px; }" +
                       ".section { margin-bottom: 20px; }" +
                       "ul { margin-top: 5px; padding-left: 20px; }";
                       
            case TYPE_3:
                // CREATIVE / MINIMALIST (Clean, spaced out, emerald accents)
                return "body { font-family: 'Arial', sans-serif; color: #1a202c; line-height: 1.7; padding: 40px; }" +
                       "h1 { font-size: 20px; color: #047857; margin-top: 25px; margin-bottom: 10px; letter-spacing: 1px; }" +
                       "h2 { font-size: 15px; color: #374151; margin-bottom: 5px; font-style: italic; }" +
                       "p, li { font-size: 12px; color: #4b5563; }" +
                       ".section { margin-bottom: 25px; border-left: 3px solid #d1fae5; padding-left: 15px; }" +
                       "ul { margin-top: 5px; padding-left: 15px; }";
                       
            case TYPE_1:
            default:
                // CLASSIC / TRADITIONAL (Serif, black and white, standard margins)
                return "body { font-family: 'Times New Roman', serif; color: #000; line-height: 1.4; padding: 25px; }" +
                       "h1 { font-size: 24px; color: #000; border-bottom: 1px solid #000; padding-bottom: 3px; margin-top: 15px; text-align: center; }" +
                       "h2 { font-size: 16px; color: #000; margin-bottom: 3px; }" +
                       "p, li { font-size: 14px; color: #000; }" +
                       ".section { margin-bottom: 15px; }" +
                       "ul { margin-top: 3px; padding-left: 25px; list-style-type: square; }";
        }
    }

    private void parseToonNode(List<Object> node, StringBuilder html, int depth) {
        if (node == null || node.size() != 3) return;

        // 1. Escape metadata if there's any chance they contain special characters
        String name = HtmlUtils.htmlEscape(String.valueOf(node.get(0))); 
        String type = String.valueOf(node.get(1));
        Object content = node.get(2);

        if ("string".equals(type)) {
            // 2. CRITICAL: Escape the actual text content being injected into the HTML body
            String safeContent = HtmlUtils.htmlEscape(String.valueOf(content));

            if (depth == 1) {
                html.append("<p><strong>").append(name).append(":</strong> ").append(safeContent).append("</p>");
            } else {
                html.append("<li>").append(safeContent).append("</li>");
            }
        } 
        else if ("array".equals(type) || "object".equals(type)) {
            if (depth == 1) {
                html.append("<div class='section'><h1>").append(name).append("</h1>");
            } else {
                html.append("<h2>").append(name).append("</h2><ul>");
            }

            if (content instanceof List) {
                List<?> children = (List<?>) content;
                for (Object child : children) {
                    if (child instanceof List) {
                        parseToonNode((List<Object>) child, html, depth + 1);
                    }
                }
            }

            if (depth == 1) {
                html.append("</div>");
            } else {
                html.append("</ul>");
            }
        }
    }
}
