server.port=8007
thirdeye.uniqueCode=abcdefgh
eureka.client.service-url.defaultZone=${THIRDEYE_RESUME_UPDATER_SERVER_URL_LOCAL}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.cache.redis.time-to-live=600000
spring.data.redis.repositories.enabled=false